# Generated by Django 5.2.5 on 2025-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientAnalysis",
            fields=[
                (
                    "desynpuf_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("age", models.IntegerField()),
                ("gender_male", models.BooleanField()),
                ("race_white", models.BooleanField()),
                ("race_black", models.BooleanField()),
                ("chronic_condition_count", models.IntegerField()),
                ("high_impact_conditions", models.TextField(blank=True, null=True)),
                ("inpatient_admissions", models.IntegerField()),
                ("inpatient_days", models.IntegerField()),
                ("outpatient_visits", models.IntegerField()),
                (
                    "total_medicare_costs",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("prior_hospitalization", models.BooleanField()),
                ("sp_chf", models.BooleanField()),
                ("sp_diabetes", models.BooleanField()),
                ("sp_chrnkidn", models.BooleanField()),
                ("sp_cncr", models.BooleanField()),
                ("sp_copd", models.BooleanField()),
                ("sp_depressn", models.BooleanField()),
                ("sp_ischmcht", models.BooleanField()),
                ("sp_strketia", models.BooleanField()),
                ("sp_alzhdmta", models.BooleanField()),
                ("sp_osteoprs", models.BooleanField()),
                ("sp_ra_oa", models.BooleanField()),
                ("risk_30d_hospitalization", models.FloatField()),
                ("risk_60d_hospitalization", models.FloatField()),
                ("risk_90d_hospitalization", models.FloatField()),
                ("mortality_risk", models.FloatField()),
                (
                    "risk_tier",
                    models.IntegerField(
                        choices=[
                            (1, "Critical"),
                            (2, "High"),
                            (3, "Medium"),
                            (4, "Low"),
                            (5, "Healthy"),
                        ]
                    ),
                ),
                ("care_intervention", models.TextField(blank=True, null=True)),
                (
                    "annual_intervention_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "cost_savings",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("prevented_hospitalizations", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "patient_analysis",
                "ordering": ["-risk_90d_hospitalization"],
                "managed": False,
            },
        ),
    ]
