# Generated by Django 5.2.5 on 2025-09-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_patientanalysis"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientanalysis",
            options={},
        ),
    ]
